### ISSUE TITLE
Long term Maintanance of the project

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/boilerplate-client-angular#340]
## Desired Use Case
I would like the project to be maintained in the future. 

## Actual/Current Behavior

The project is currently being maintained by whomever is creating new features, which makes maintenance a reactionary procedure. This will decrease velocity in the long run. 

  1. Fork the project
  2.Wait 4 months
  3. See Dependencies out of date

## Learning

Im thinking that we can head off some of these issues by adding Dependabot to our repo. It will at least let us know about any security vulns and potentially non-breaking fixes.

**Comment by michaelachrisco** [comment]
@22antonio Let me know if you have any questions on this.

**Comment by 22antonio** [comment]
The error I'm getting right now
```
boilerplate-client-angular (am-340-long-term-maintenance) # npm run e2e

> boilerplate-client-angular@0.5.4 e2e
> ng e2e --port 4201

[10:01:56] I/update - chromedriver: file exists /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/webdriver-manager/selenium/chromedriver_95.0.4638.69.zip
[10:01:56] I/update - chromedriver: unzipping chromedriver_95.0.4638.69.zip
[10:01:57] I/update - chromedriver: setting permissions to 0755 for /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/webdriver-manager/selenium/chromedriver_95.0.4638.69
[10:01:57] I/update - chromedriver: chromedriver_95.0.4638.69 up to date

chunk {common} common.js, common.js.map (common) 4.04 kB  [rendered]
chunk {default~features-admin-admin-module~features-content-content-module~features-user-user-module} default~features-admin-admin-module~features-content-content-module~features-user-user-module.js, default~features-admin-admin-module~features-content-content-module~features-user-user-module.js.map (default~features-admin-admin-module~features-content-content-module~features-user-user-module) 57.6 kB  [rendered]
chunk {default~features-admin-admin-module~features-user-user-module} default~features-admin-admin-module~features-user-user-module.js, default~features-admin-admin-module~features-user-user-module.js.map (default~features-admin-admin-module~features-user-user-module) 18.3 kB  [rendered]
chunk {features-admin-admin-module} features-admin-admin-module.js, features-admin-admin-module.js.map (features-admin-admin-module) 103 kB  [rendered]
chunk {features-auth-auth-module} features-auth-auth-module.js, features-auth-auth-module.js.map (features-auth-auth-module) 102 kB  [rendered]
chunk {features-content-content-module} features-content-content-module.js, features-content-content-module.js.map (features-content-content-module) 74.3 kB  [rendered]
chunk {features-user-user-module} features-user-user-module.js, features-user-user-module.js.map (features-user-user-module) 26.4 kB  [rendered]
chunk {main} main.js, main.js.map (main) 245 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 212 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.53 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.03 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.97 MB [initial] [rendered]
Date: 2021-11-09T18:02:10.755Z - Hash: 5accdcb428282c590a2d - Time: 11156ms
** Angular Live Development Server is listening on localhost:4201, open your browser on http://localhost:4201/ **
: Compiled successfully.
[10:02:11] I/launcher - Running 1 instances of WebDriver
[10:02:11] I/hosted - Using the selenium server at http://localhost:4445/wd/hub/
[10:02:12] E/launcher - Error: TypeError: SpecReporter is not a constructor
    at onPrepare (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/e2e/protractor.conf.js:34:20)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/protractor/built/util.js:46:49
    at Function.promise (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:682:9)
    at Object.runFilenameOrFn_ (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/protractor/built/util.js:38:16)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/protractor/built/runner.js:98:27
    at _fulfilled (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:834:54)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:796:13)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:556:49
    at runSingle (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:137:13)
[10:02:12] E/launcher - Process exited with error code 100
```

I was finally able to get the WebDriver to run and it hosts a selenium server to run all the protractor tests. However it crashes with the error above. I've looked up this issue and I've already implemented this [fix](https://stackoverflow.com/questions/43001079/specreporter-is-not-a-constructor-error-when-running-protractor-using-angular-cl). I'm determined to get this working. I'm currently looking for another solution.

**Comment by 22antonio** [comment]
Does anyone know how to make protractor see the Driver version? It's funding the driver but I'm not sure if I need to explicitly show it the location. 

```
[10:21:57] I/update - chromedriver: file exists /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/webdriver-manager/selenium/chromedriver_95.0.4638.69.zip
[10:21:57] I/update - chromedriver: unzipping chromedriver_95.0.4638.69.zip
[10:21:57] I/update - chromedriver: setting permissions to 0755 for /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/webdriver-manager/selenium/chromedriver_95.0.4638.69
[10:21:57] I/update - chromedriver: chromedriver_95.0.4638.69 up to date

chunk {common} common.js, common.js.map (common) 4.04 kB  [rendered]
chunk {default~features-admin-admin-module~features-content-content-module~features-user-user-module} default~features-admin-admin-module~features-content-content-module~features-user-user-module.js, default~features-admin-admin-module~features-content-content-module~features-user-user-module.js.map (default~features-admin-admin-module~features-content-content-module~features-user-user-module) 57.6 kB  [rendered]
chunk {default~features-admin-admin-module~features-user-user-module} default~features-admin-admin-module~features-user-user-module.js, default~features-admin-admin-module~features-user-user-module.js.map (default~features-admin-admin-module~features-user-user-module) 18.3 kB  [rendered]
chunk {features-admin-admin-module} features-admin-admin-module.js, features-admin-admin-module.js.map (features-admin-admin-module) 103 kB  [rendered]
chunk {features-auth-auth-module} features-auth-auth-module.js, features-auth-auth-module.js.map (features-auth-auth-module) 102 kB  [rendered]
chunk {features-content-content-module} features-content-content-module.js, features-content-content-module.js.map (features-content-content-module) 74.3 kB  [rendered]
chunk {features-user-user-module} features-user-user-module.js, features-user-user-module.js.map (features-user-user-module) 26.4 kB  [rendered]
chunk {main} main.js, main.js.map (main) 245 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 212 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.53 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.03 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.97 MB [initial] [rendered]
Date: 2021-11-09T18:22:12.445Z - Hash: 5accdcb428282c590a2d - Time: 11637ms
** Angular Live Development Server is listening on localhost:4201, open your browser on http://localhost:4201/ **
: Compiled successfully.
[10:22:12] I/launcher - Running 1 instances of WebDriver
[10:22:12] I/local - Starting selenium standalone server...
[10:22:13] I/local - Selenium standalone server started at http://192.168.1.4:61427/wd/hub
[10:22:33] E/launcher - Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Tonys-MBP-88.lan', ip: '2603:9008:2501:d13a:0:0:0:13af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.0.1', java.version: '17.0.1'
Driver info: driver.version: unknown
[10:22:33] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Tonys-MBP-88.lan', ip: '2603:9008:2501:d13a:0:0:0:13af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.0.1', java.version: '17.0.1'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/selenium-webdriver/index.js:626:16)
    at Local.getNewDriver (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/protractor/built/runner.js:195:43)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:834:54)
    at /Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/tonymedel/Documents/Projects/bp-client-issues/boilerplate-client-angular/node_modules/q/q.js:796:13)
[10:22:33] E/launcher - Process exited with error code 199
```

**Comment by michaelachrisco** [comment]
@22antonio I would recommend asking the above question within the tech-discussions slack channel. We may have had individuals solve this issue before.
